### ISSUE TITLE
add support for import opml file will be better

### ISSUE THREAD

**Issue by b1tg** [ww9/news#1]
awesome project !
i have a opml file export from another rss reader, if news can import opml, it will be more convenient.

**Comment by ww9** [comment]
Hi, I'm so sorry I took this long to answer you. Somehow I missed the notification.

Yes, importing opml files would be very convenient for users migrating from other readers. I'll try to implement it.

Thank you for suggesting it!

**Comment by ww9** [comment]
Added support for importing OPML files. Pass `-opml filename.opml` as command-line argument.

![image](https://user-images.githubusercontent.com/27555162/48806573-82c8a700-ecf9-11e8-9b7a-252d1cab5953.png)

Let me know if you have any issue.
